version: '3'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 nike_shoes_store.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=nike_shoes_store.settings_prod
      - SECRET_KEY=django-insecure-key-for-development-only
      - ALLOWED_HOSTS=localhost,127.0.0.1

  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: